---
- hosts: all
  name: Basic Raspberry Pi Setup
  tasks:
    - name: Set up basic facts
      ansible.builtin.set_fact:
        home_dir: "{{ ansible_env['HOME'] }}"
        distro: "{{ ansible_distribution_release }}"
        smb_user: "bkuser"
        enabled: true

    - name: Read list of files to install with apt
      ansible.builtin.set_fact:
        apt_list: "{{ item.split('\n') }}"
      with_file: "{{ playbook_dir }}/apt.list"

    - name: Read list of files to install with pip
      ansible.builtin.set_fact:
        pip_list: "{{ item.split('\n') }}"
      with_file: "{{ playbook_dir }}/pip.list"

    - name: Read smb password
      ansible.builtin.set_fact:
        smb_password: "{{ item }}"
      with_file: "{{ playbook_dir }}/secrets/smbpasswd"

    - name: Set Local Timezone
      ansible.builtin.shell: |
        set -e -o pipefail
        timedatectl set-timezone Europe/Warsaw
      args:
        executable: /bin/bash
      become: true
      when: enabled

    - name: Copy rc files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ home_dir }}/"
        mode: '0644'
      with_fileglob: "{{ playbook_dir }}/config/rc/*"
      when: enabled

    - name: Copy bash source files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ home_dir }}/"
        mode: '0644'
      with_fileglob: "{{ playbook_dir }}/config/source/*"
      when: enabled

    - name: Create Secrets Directory
      ansible.builtin.file:
        path: "{{ home_dir }}/secrets"
        state: directory
        mode: '0700'
      when: enabled

    - name: Copy SSH Private Key
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/secrets/ssh/id_rsa"
        dest: "~/.ssh/id_rsa"
        mode: '0600'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
      become: true
      when: enabled

    - name: Copy SSH Authorized Keys
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/secrets/ssh/authorized_keys"
        dest: "~/.ssh/authorized_keys"
        mode: '0600'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
      become: true
      when: enabled

    - name: Copy SSH Known Hosts
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/secrets/ssh/known_hosts"
        dest: "~/.ssh/known_hosts"
        mode: '0600'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
      become: true
      when: enabled

    - name: Copy SSH Public Key
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/secrets/ssh/id_rsa.pub"
        dest: "~/.ssh/id_rsa.pub"
        mode: '0644'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
      become: true
      when: enabled

    - name: Add GitHub as known_host
      ansible.builtin.shell: |
        ssh -oStrictHostKeyChecking=accept-new git@github.com || true
      args:
        executable: /bin/bash
      when: enabled

    - name: Find Files to Add to .bashrc
      ansible.builtin.find:
        path: "{{ home_dir }}"
        pattern: "source_*"
      register: source_files
      when: enabled

    - name: Add source to all source files in bashrc
      ansible.builtin.lineinfile:
        path: "{{ home_dir }}/.bashrc"
        line: ". {{ item.path }}"
      with_items: "{{ source_files.files }}"
      when: enabled

    - name: Export GH_TOKEN is .bashrc
      ansible.builtin.lineinfile:
        path: "{{ home_dir }}/.bashrc"
        line: "export GH_TOKEN=$(cat ~/secrets/github.token)"
      when: enabled

    - name: Disable login with password
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: '^PasswordAuthentication '
        line: "PasswordAuthentication no"
      become: true
      when: enabled

    - name: Replace /etc/apt/sources.list
      ansible.builtin.template:
        src: "{{ playbook_dir }}/sources_template.j2"
        dest: "/etc/apt/sources.list"
        backup: true
        mode: '0644'
      become: true
      when: enabled

    - name: Update Packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: "dist"
      become: true
      when: enabled

    - name: Install Basic Packages
      ansible.builtin.apt:
        name: [
          apt-transport-https,
          ca-certificates,
          curl,
          gnupg-agent,
          software-properties-common,
          apt-utils
        ]
      become: true
      when: enabled

    - name: Add Docker Repo
      ansible.builtin.shell: |
        set -e -o pipefail
        sudo rm -f /etc/apt/keyrings/docker.gpg;
        sudo install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
        sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        sudo chmod a+r /etc/apt/keyrings/docker.gpg
        echo \
        "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        executable: /bin/bash
      become: true
      when: enabled

    - name: Add gh Repo
      ansible.builtin.shell: |
        set -e -o pipefail
        KEYRING=/etc/apt/keyrings/githubcli-archive-keyring.gpg
        sudo rm -f $KEYRING;
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \
        | sudo dd of=$KEYRING
        echo "deb [arch=$(dpkg --print-architecture) signed-by=$KEYRING] https://cli.github.com/packages stable main" \
        | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
      args:
        executable: /bin/bash
      become: true
      when: enabled

    - name: Add qBittorrent Repo
      ansible.builtin.apt_repository:
        repo: ppa:qbittorrent-team/qbittorrent-stable
      become: true
      when: enabled

    - name: Add Neovim Unstable Repo
      ansible.builtin.apt_repository:
        repo: ppa:neovim-ppa/unstable
      become: true
      when: enabled

    - name: Add Terraform Repo
      ansible.builtin.shell: |
        set -e -o pipefail
        sudo rm -f /etc/apt/keyrings/hashicorp-archive-keyring.gpg;
        sudo install -m 0755 -d /etc/apt/keyrings
        wget -O- https://apt.releases.hashicorp.com/gpg | \
        gpg --dearmor | \
        sudo tee /etc/apt/keyrings/hashicorp-archive-keyring.gpg > /dev/null
        echo "deb [signed-by=/etc/apt/keyrings/hashicorp-archive-keyring.gpg] \
        https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
        sudo tee /etc/apt/sources.list.d/hashicorp.list > /dev/null
      args:
        executable: /bin/bash
      become: true
      when: enabled

    - name: Add Vagrant Repo
      ansible.builtin.shell: |
        set -e -o pipefail
        KEYRING=/etc/apt/keyrings/hashicorp-archive-keyring.gpg
        sudo rm -f $KEYRING;
        sudo install -m 0755 -d /etc/apt/keyrings
        wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o $KEYRING
        echo "deb [signed-by=$KEYRING] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list > /dev/null
      args:
        executable: /bin/bash
      become: true
      when: enabled

    - name: Add kubectl Repo
      ansible.builtin.shell: |
        set -eux
        set -o pipefail
        KEYRING=/etc/apt/keyrings/kubernetes-archive-keyring.gpg
        sudo rm -f $KEYRING;
        curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o $KEYRING
        echo "deb [signed-by=$KEYRING] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list > /dev/null
      args:
        executable: /bin/bash
      become: true
      when: enabled

    - name: Install APT Packages
      ansible.builtin.apt:
        update_cache: true
        name: "{{ apt_list }}"
      become: true
      when: enabled

    - name: Add User to Docker Group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
      become: true
      when: enabled

    # - name: Install pip Packages
    #   ansible.builtin.pip:
    #     name: "{{ pip_list }}"
    #     executable: "pip3"
    #   become: true
    #   when: enable
    
    - name: Install fancygit
      ansible.builtin.shell: |
        set -eux
        set -o pipefail
        rm -rf $HOME/.fancy-git
        # curl -sS https://raw.githubusercontent.com/diogocavilha/fancy-git/master/uninstall.sh | sh
        curl -sS https://raw.githubusercontent.com/diogocavilha/fancy-git/master/install.sh | sh
        sh ~/.fancy-git/commands-handler.sh --theme-simple
        sh ~/.fancy-git/commands-handler.sh --disable-time
        sh ~/.fancy-git/commands-handler.sh --enable-double-line
        sh ~/.fancy-git/commands-handler.sh --enable-bold-prompt
        sh ~/.fancy-git/commands-handler.sh --disable-rich-notification
      args:
        executable: /bin/bash
      become: false
      when: enabled

    - name: Install rust
      ansible.builtin.shell: |
        set -e
        set -o pipefail
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile complete
      args:
        executable: /bin/bash
      become: false
      when: enabled

    - name: Create Secrets Directory
      ansible.builtin.file:
        path: "/mnt/bk"
        state: directory
        mode: '0777'
      become: true
      when: enabled

    - name: Add mount to Seagate
      ansible.builtin.lineinfile:
        path: "/etc/fstab"
        line: "UUID=09eac762-c108-4d59-bf52-4dc04a9f0e98 /mnt/bk ext4 rw,relatime,discard 0 0"
      become: true
      when: enabled

    - name: Add samba config
      ansible.builtin.blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [sambashare]
              comment = Samba on Ubuntu
              path = /mnt/bk
              read only = no
              browsable = true
      become: true
      when: enabled

    - name: Restart SAMBA
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: smbd
      become: true
      when: enabled

    - name: Allow SAMBA in Firewall
      ansible.builtin.shell: |
        ufw allow samba
      become: true
      when: enabled

    - name: Add SAMBA user
      ansible.builtin.user:
        name: "{{ smb_user }}"
        create_home: false
        password: '*'
      become: true
      when: enabled

    - name: Add Samba User to gpio Group
      ansible.builtin.user:
        name: "{{ smb_user }}"
        groups: gpio
        append: true
      become: true
      when: enabled

    - name: Set SAMBA password
      ansible.builtin.shell: |
        smbpasswd -x {{ smb_user }} || true;
        smbpasswd -a -s {{ smb_user }}
      args:
        stdin: "{{ smb_password }}"
        stdin_add_newline: true
        executable: /bin/bash
      become: true
      when: enabled

    - name: Reboot
      ansible.builtin.reboot:
      become: true
      when: enabled

    - name: Check Mount /mnt/bk
      ansible.builtin.shell: |
        ls /mnt/bk
      args:
        executable: /bin/bash
      become: false
      when: enabled

    - name: Check Docker
      ansible.builtin.shell: |
        docker run hello-world
        docker compose version
      args:
        executable: /bin/bash
      become: false
      when: enabled

    - name: Check rust
      ansible.builtin.shell: |
        ~/.cargo/bin/cargo -V && ~/.cargo/bin/rustc -V
      args:
        executable: /bin/bash
      become: false
      when: enabled

    - name: Check Hashicorp Software
      ansible.builtin.shell: |
        terraform -v && vagrant -v
      args:
        executable: /bin/bash
      become: false
      when: enabled

    # - name: Debug
    #   ansible.builtin.debug:
    #     msg: "{{ apt_list }}"
    #     msg: "{{ rc_files[0] }}"
