---
- hosts: all
  name: Basic Raspberry Pi Setup
  tasks:
    - name: Set up basic facts
      set_fact:
        home_dir: "{{ ansible_env['HOME'] }}"
        distro: "{{ ansible_distribution_release }}"
        smb_user: "bkuser"
        enabled: yes

    - name: Read list of files to install with apt
      set_fact:
        apt_list: "{{ item.split('\n') }}"
      with_file: "{{ playbook_dir }}/apt.list"

    - name: Read list of files to install with pip
      set_fact:
        pip_list: "{{ item.split('\n') }}"
      with_file: "{{ playbook_dir }}/pip.list"

    - name: Read smb password
      set_fact:
        smb_password: "{{ item }}"
      with_file: "{{ playbook_dir }}/secrets/smbpasswd"

    - name: Set Local Timezone
      ansible.builtin.shell: |
        timedatectl set-timezone Europe/Warsaw
      become: yes
      when: enabled

    - name: Copy rc files
      copy:
        src: "{{ item }}"
        dest: "{{ home_dir }}/"
      with_fileglob: "{{ playbook_dir }}/config/rc/*"
      when: enabled

    - name: Copy bash source files
      copy:
        src: "{{ item }}"
        dest: "{{ home_dir }}/"
      with_fileglob: "{{ playbook_dir }}/config/source/*"
      when: enabled

    - name: Create Secrets Directory
      ansible.builtin.file:
        path: "{{ home_dir }}/secrets"
        state: directory
        mode: '0700'
      when: enabled

    - name: Copy Secrets
      copy:
        src: "{{ item }}"
        dest: "{{ home_dir }}/secrets/"
        mode: '0600'
      with_fileglob: "{{ playbook_dir}}/secrets/*"
      when: no

    - name: Find Files to Add to .bashrc
      find:
        path: "{{ home_dir }}"
        pattern: "source_*"
      register: source_files
      when: enabled

    - name: Add source to all source files in bashrc
      ansible.builtin.lineinfile:
        path: "{{ home_dir }}/.bashrc"
        line: ". {{ item.path }}"
      with_items: "{{source_files.files}}"
      when: enabled

    - name: Export GH_TOKEN is .bashrc
      ansible.builtin.lineinfile:
        path: "{{ home_dir }}/.bashrc"
        line: "export GH_TOKEN=$(cat ~/secrets/github.token)"
      when: no

    - name: Disable login with password
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: '^PasswordAuthentication '
        line: "PasswordAuthentication no"
      become: yes
      when: no

    - name: Replace /etc/apt/sources.list
      template:
        src: "{{ playbook_dir }}/sources_template.j2"
        dest: "/etc/apt/sources.list"
        backup: yes
      become: yes
      when: enabled

    - name: Update Packages
      apt:
        update_cache: yes
        upgrade: "dist"
      become: yes
      when: enabled

    - name: Install Basic Packages
      apt:
        name: [
          apt-transport-https,
          ca-certificates,
          curl,
          gnupg-agent,
          software-properties-common,
          apt-utils
        ]
      become: yes
      when: enabled

    - name: Add Docker Repo Key
      ansible.builtin.shell: |
        sudo rm -f /etc/apt/keyrings/docker.gpg;
        sudo mkdir -p /etc/apt/keyrings;
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
        | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      become: yes
      when: enabled

    - name: Add Docker Repo
      ansible.builtin.shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
        https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
        | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      become: yes
      when: enabled

    - name: Add PostgreSQL Repository
      ansible.builtin.shell: |
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list';
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
      become: yes
      when: enabled

    - name: Add gh Repo Key
      ansible.builtin.shell: |
        sudo rm /usr/share/keyrings/githubcli-archive-keyring.gpg;
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \
        | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
      become: yes
      when: enabled

    - name: Add gh Repo
      ansible.builtin.shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
        | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
      become: yes
      when: enabled

    - name: Install APT Packages
      apt:
        update_cache: yes
        name: "{{ apt_list }}"
      become: yes
      when: enabled

    - name: Add User to Docker Group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: yes
      when: enabled

    - name: Install PiP Packages
      pip:
        name: "{{ pip_list }}"
        executable: "pip3"
      become: yes
      when: enabled

    - name: Create Secrets Directory
      ansible.builtin.file:
        path: "/mnt/bk"
        state: directory
        mode: '0777'
      become: yes
      when: enabled

    - name: Add mount to Seagate
      ansible.builtin.lineinfile:
        path: "/etc/fstab"
        line: "UUID=5B5DDCFA0CCCCA80 /mnt/bk ntfs defaults 0 0"
      become: yes
      when: enabled

    - name: Add samba config
      ansible.builtin.blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [sambashare]
              comment = Samba on Ubuntu
              path = /mnt/bk
              read only = no
              browsable = yes
      become: yes
      when: enabled

    - name: Restart SAMBA
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: smbd
      become: yes
      when: enabled

    - name: Allow SAMBA in Firewall
      ansible.builtin.shell: |
        ufw allow samba
      become: yes
      when: enabled

    - name: Add SAMBA user
      ansible.builtin.user:
        name: "{{ smb_user }}"
        create_home: no
        password: '*'
      become: yes
      when: enabled

    - name: Set SAMBA password
      ansible.builtin.shell: |
        smbpasswd -x {{ smb_user }} || true;
        smbpasswd -a -s {{ smb_user }}
      args:
        stdin: "{{ smb_password }}"
        stdin_add_newline: yes
      become: yes
      when: enabled

    - name: Reboot
      reboot:
      become: yes
      when: enabled

    - name: Debug
      debug:
        msg: "{{ apt_list }}"
        # msg: "{{ rc_files[0] }}"
