---
- hosts: all
  name: Basic Raspberry Pi Setup
  tasks:
    - name: Set up basic facts
      set_fact:
        home_dir: "{{ ansible_env['HOME'] }}"
        distro: "{{ ansible_distribution_release }}"
        enabled: yes

    - name: Read list of files to install with apt
      set_fact:
        apt_list: "{{ item.split('\n') }}"
      with_file: "{{ playbook_dir }}/apt.list"

    - name: Read list of files to install with pip
      set_fact:
        pip_list: "{{ item.split('\n') }}"
      with_file: "{{ playbook_dir }}/pip.list"

    - name: Set Local Timezone
      shell: >
        timedatectl set-timezone Europe/Warsaw
      become: yes
      when: enabled

    - name: Copy rc files
      copy:
        src: "{{ item }}"
        dest: "{{ home_dir }}/"
      with_fileglob: "{{ playbook_dir }}/configs/*rc"
      when: enabled

    - name: Copy bash source files
      copy:
        src: "{{ item }}"
        dest: "{{ home_dir }}/"
      with_fileglob: "{{ playbook_dir }}/configs/source*"
      when: enabled

    - name: Create Secrets Directory
      ansible.builtin.file:
        path: "{{ home_dir }}/secrets"
        state: directory
        mode: '0700'
      when: enabled

    - name: Copy Secrets
      copy:
        src: "{{ item }}"
        dest: "{{ home_dir }}/secrets/"
        mode: '0600'
      with_fileglob: "{{ playbook_dir}}/secrets/*"
      when: no

    - name: Find Files to Add to .bashrc
      find:
        path: "{{ home_dir }}"
        pattern: "source_*"
      register: source_files
      when: enabled

    - name: Add source to all source files in bashrc
      lineinfile:
        path: "{{ home_dir }}/.bashrc"
        line: ". {{ item.path }}"
      with_items: "{{source_files.files}}"
      when: enabled

    - name: Export GH_TOKEN is .bashrc
      lineinfile:
        path: "{{ home_dir }}/.bashrc"
        line: "export GH_TOKEN=$(cat ~/secrets/github.token)"
      when: no

    - name: Disable login with password
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: '^PasswordAuthentication '
        line: "PasswordAuthentication no"
      become: yes
      when: no

    - name: Replace /etc/apt/sources.list
      template:
        src: "{{ playbook_dir }}/sources_template.j2"
        dest: "/etc/apt/sources.list"
        backup: yes
      become: yes
      when: enabled

    - name: Update Packages
      apt:
        update_cache: yes
        upgrade: "dist"
      become: yes
      when: enabled

    - name: Install Basic Packages
      apt:
        name: [
          apt-transport-https,
          ca-certificates,
          curl,
          gnupg-agent,
          software-properties-common,
          apt-utils
        ]
      become: yes
      when: enabled

    - name: Add Docker Repo Key
      shell: >
        sudo rm /usr/share/keyrings/docker-archive-keyring.gpg;
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg 
        | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        warn: no
      become: yes
      when: enabled

    - name: Add Docker Repo
      shell: >
        echo "deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] 
        https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" 
        | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      become: yes
      when: enabled

    - name: Add PostgreSQL Repository
      shell: >
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list';
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
      args:
        warn: no
      become: yes
      when: yes

    - name: Add gh Repo Key
      shell: >
        sudo rm /usr/share/keyrings/githubcli-archive-keyring.gpg;
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg 
        | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
      args:
        warn: no
      become: yes
      when: no
    
    - name: Add gh Repo
      shell: >
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" 
        | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
      args:
        warn: no
      become: yes
      when: no

    - name: Install APT Packages
      apt:
        update_cache: yes
        name: "{{ apt_list }}"
      become: yes
      when: enabled

    - name: Add User to Docker Group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: yes
      when: enabled

    - name: Install PiP Packages
      pip:
        name: "{{ pip_list }}"
        executable: "pip3"
      become: yes
      when: enabled

    - name: Reboot
      reboot:
      become: yes
      when: enabled

    - name: Debug
      debug:
        msg: "{{ apt_list }}"
        # msg: "{{ rc_files[0] }}"
